options(prompt="R>", scipen=100, digits=4)

#FEMALE LENGTH
library(readxl)
unifl=read_excel("0-reps-10.xlsx", sheet="female-lengths")
#generate univarate values for entry into "baboonFA-10reps-psworksheet.xlsx"
cat("MNM1")
summary(aov(mnm1 ~ Side + Side*Ind + Error(Ind/(Side*Ind)), data=unifl))
cat("\n","MNM2", "*********************")
summary(aov(mnm2 ~ Side + Side*Ind + Error(Ind/(Side*Ind)), data=unifl))
cat("\n","MNM3", "*********************")
summary(aov(mnm3 ~ Side + Side*Ind + Error(Ind/(Side*Ind)), data=unifl))
cat("\n","MNP4", "*********************")
summary(aov(mnp4 ~ Side + Side*Ind + Error(Ind/(Side*Ind)), data=unifl))
cat("\n","MXM1","*********************")
summary(aov(mxm1 ~ Side + Side*Ind + Error(Ind/(Side*Ind)), data=unifl))
cat("\n","MXM2","*********************")
summary(aov(mxm2 ~ Side + Side*Ind + Error(Ind/(Side*Ind)), data=unifl))
cat("\n","MXM3","*********************")
summary(aov(mxm3 ~ Side + Side*Ind + Error(Ind/(Side*Ind)), data=unifl))
cat("\n","MXP3","*********************")
summary(aov(mxp3 ~ Side + Side*Ind + Error(Ind/(Side*Ind)), data=unifl))
cat("\n","MXP4","*********************")
summary(aov(mxp4 ~ Side + Side*Ind + Error(Ind/(Side*Ind)), data=unifl))

#MALE LENGTH
library(readxl)
uniml=read_excel("0-reps-10.xlsx", sheet="male-lengths")
#generate univarate values for entry into "baboonFA-10reps-psworksheet.xlsx"
cat("MNM1")
summary(aov(mnm1 ~ Side + Side*Ind + Error(Ind/(Side*Ind)), data=uniml))
cat("\n","MNM2", "*********************")
summary(aov(mnm2 ~ Side + Side*Ind + Error(Ind/(Side*Ind)), data=uniml))
cat("\n","MNM3", "*********************")
summary(aov(mnm3 ~ Side + Side*Ind + Error(Ind/(Side*Ind)), data=uniml))
cat("\n","MNP4", "*********************")
summary(aov(mnp4 ~ Side + Side*Ind + Error(Ind/(Side*Ind)), data=uniml))
cat("\n","MXM1","*********************")
summary(aov(mxm1 ~ Side + Side*Ind + Error(Ind/(Side*Ind)), data=uniml))
cat("\n","MXM2","*********************")
summary(aov(mxm2 ~ Side + Side*Ind + Error(Ind/(Side*Ind)), data=uniml))
cat("\n","MXM3","*********************")
summary(aov(mxm3 ~ Side + Side*Ind + Error(Ind/(Side*Ind)), data=uniml))
cat("\n","MXP3","*********************")
summary(aov(mxp3 ~ Side + Side*Ind + Error(Ind/(Side*Ind)), data=uniml))
cat("\n","MXP4","*********************")
summary(aov(mxp4 ~ Side + Side*Ind + Error(Ind/(Side*Ind)), data=uniml))

#FEMALE-BREADTH
library(readxl)
unifb=read_excel("0-reps-10.xlsx", sheet="female-breadths")
#generate univarate values for entry into "baboonFA-10reps-psworksheet.xlsx"
cat("MNM1")
summary(aov(mnm1 ~ Side + Side*Ind + Error(Ind/(Side*Ind)), data=unifb))
cat("\n","MNM2", "*********************")
summary(aov(mnm2 ~ Side + Side*Ind + Error(Ind/(Side*Ind)), data=unifb))
cat("\n","MNM3", "*********************")
summary(aov(mnm3 ~ Side + Side*Ind + Error(Ind/(Side*Ind)), data=unifb))
cat("\n","MNP4", "*********************")
summary(aov(mnp4 ~ Side + Side*Ind + Error(Ind/(Side*Ind)), data=unifb))
cat("\n","MXM1","*********************")
summary(aov(mxm1 ~ Side + Side*Ind + Error(Ind/(Side*Ind)), data=unifb))
cat("\n","MXM2","*********************")
summary(aov(mxm2 ~ Side + Side*Ind + Error(Ind/(Side*Ind)), data=unifb))
cat("\n","MXM3","*********************")
summary(aov(mxm3 ~ Side + Side*Ind + Error(Ind/(Side*Ind)), data=unifb))
cat("\n","MXP3","*********************")
summary(aov(mxp3 ~ Side + Side*Ind + Error(Ind/(Side*Ind)), data=unifb))
cat("\n","MXP4","*********************")
summary(aov(mxp4 ~ Side + Side*Ind + Error(Ind/(Side*Ind)), data=unifb))

#MALE BREADTH
library(readxl)
unimb=read_excel("0-reps-10.xlsx", sheet="male-breadths")
unimb$mnm1=as.numeric(unimb$mnm1)
#generate univarate values for entry into "baboonFA-10reps-psworksheet.xlsx"
cat("MNM1")
summary(aov(mnm1 ~ Side + Side*Ind + Error(Ind/(Side*Ind)), data=unimb))
cat("\n","MNM2", "*********************")
summary(aov(mnm2 ~ Side + Side*Ind + Error(Ind/(Side*Ind)), data=unimb))
cat("\n","MNM3","*********************")
summary(aov(mnm3 ~ Side + Side*Ind + Error(Ind/(Side*Ind)), data=unimb))
cat("\n","MNP4","*********************")
summary(aov(mnp4 ~ Side + Side*Ind + Error(Ind/(Side*Ind)), data=unimb))
cat("\n","MXM1","*********************")
summary(aov(mxm1 ~ Side + Side*Ind + Error(Ind/(Side*Ind)), data=unimb))
cat("\n","MXM2","*********************")
summary(aov(mxm2 ~ Side + Side*Ind + Error(Ind/(Side*Ind)), data=unimb))
cat("\n","MXM3","*********************")
summary(aov(mxm3 ~ Side + Side*Ind + Error(Ind/(Side*Ind)), data=unimb))
cat("\n","MXP3","*********************")
summary(aov(mxp3 ~ Side + Side*Ind + Error(Ind/(Side*Ind)), data=unimb))
cat("\n","MXP4","*********************")
summary(aov(mxp4 ~ Side + Side*Ind + Error(Ind/(Side*Ind)), data=unimb))


